logger:
  file:
    path: /h-nssf.log
#  level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

nssf:
  sbi:
    server:
      - address: nssf.5gc.mnc070.mcc999.3gppnetwork.org
    client:
#      nrf:
#        - uri: http://127.0.0.10:7777
      scp:
        - uri: http://127.0.1.200:7777
      nsi:
        - uri: http://nrf.5gc.mnc070.mcc999.3gppnetwork.org
          s_nssai:
            sst: 1