logger:
  file:
    path: /upf.log
#  level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

upf:
  pfcp:
    server:
      - address: 127.0.1.7
    client:
#      smf:     #  UPF PFCP Client try to associate SMF PFCP Server
#        - address: 127.0.1.4
  gtpu:
    server:
      - address: 127.0.1.7
  session:
    - subnet: 10.46.0.0/16
      gateway: 10.46.0.1
      dev: ogstun2
    - subnet: 2001:db8:babe::/48
      gateway: 2001:db8:babe::1
      dev: ogstun2
  metrics:
    server:
      - address: 127.0.1.7
        port: 9090