# Example config for a locally deployed CU listening on the localhost interface for a DU connection

gnb_id: 411                                        # Optional UINT (411). Sets the numerical ID associated with the gNB.
gnb_id_bit_length: 22
ran_node_name: cu_cp_01 

cu_cp:
  max_nof_dus: 4                     
  max_nof_cu_ups: 4                 
  amf:
    addr: 127.0.2.5                                # The address or hostname of the AMF.
    port: 38412
    bind_addr: 127.0.0.1                           # A local IP that the gNB binds to for traffic from the AMF.
    supported_tracking_areas:                      # Configure the TA associated with the CU-CP
      - tac: 7                                     # Tracking area code
        plmn_list:                                 # List of PLMNs associated with the tracking area
          - plmn: "NETWORK_MCCNETWORK_MNC"         # PLMN ID
            tai_slice_support_list:                # List of slices supported by the tracking area
              - sst: 1                             # Slice/Service Type
  f1ap:
    bind_addr: 127.0.10.1                          # Configure the F1AP bind address, this will enable the CU-cp to connect to the DU
  
  mobility:
    trigger_handover_from_measurements: false                    # Set the CU-CP to trigger handover when neighbor cell measurements arrive
    cells:                                                      # List of cells available for handover known to the cu-cp
      - nr_cell_id: 0x66C001                                        # Cell ID for cell 1
        periodic_report_cfg_id: 1                                 # Set the periodic report configuration ID for this cell
        ncells:                                                   # Neighbor cell(s) available for handover
          - nr_cell_id: 0x66C002                                      # Cell ID of neighbor cell available for handover
            report_configs: [ 2 ]                                   # Report configurations to configure for this neighbor cell
      - nr_cell_id: 0x66C002                                        # Cell ID for cell 2
        periodic_report_cfg_id: 1                                 # Set the periodic report configuration ID for this cell
        ncells:                                                   # Neighbor cell(s) available for handover
          - nr_cell_id: 0x66C001                                      # Cell ID of neighbor cell available for handover
            report_configs: [ 2 ]                                   # Report configurations to configure for this neighbor cell
    report_configs:                           
      - report_cfg_id: 1                      
        report_type: periodical               
        report_interval_ms: 480                 
      - report_cfg_id: 2                        
        report_type: event_triggered            
        event_triggered_report_type: a3                           # Sets the event triggered report type as A3
        meas_trigger_quantity: rsrp                               # Sets the measurement trigger quantity as rsrp
        meas_trigger_quantity_offset_db: 6                         # Sets the measurement trigger quantity offset to 3dB
        hysteresis_db: 3                                          # Sets the hysteresis to 0dB
        time_to_trigger_ms: 320                                   # Sets the time to trigger to 100ms

cu_up:
  f1u:
    socket:                                        # Define UDP/IP socket(s) for F1-U interface.
      - bind_addr: 127.0.10.1                      # Sets the address that the F1-U socket will bind to.

log:
  filename: /tmp/cu.log
  all_level: warning

pcap:
  ngap_enable: false
  ngap_filename: /tmp/cu_ngap.pcap