# Example config for a DU with one 20MHz TDD cell using a USRP as RF frontend.
gnb_id: 411                                                     #Optional UINT (411). Sets the numerical ID associated with the gNB.
gnb_id_bit_length: 22
gnb_du_id: 1

f1ap:
  cu_cp_addr: 127.0.10.1
  bind_addr: 127.0.10.3

f1u:
  socket:
    - bind_addr: 127.0.10.3

ru_sdr:
  device_driver: uhd
  device_args: type=b200,serial=USRP_ID,num_recv_frames=256,num_send_frames=256
  srate: 23.04
  otw_format: sc12  
  tx_gain: 80
  rx_gain: 40

cell_cfg:
  dl_arfcn: 503340
  band: 41                         
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "NETWORK_MCCNETWORK_MNC"
  tac: 7                            
  pci: 2
  sector_id: 0011
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  pdsch:
    mcs_table: qam256 

log:
  filename: /tmp/du_b205.log
  all_level: debug

pcap:
  mac_enable: false
  mac_filename: /tmp/du_b205_mac.pcap
  f1ap_enable: false
  f1ap_filename: /tmp/du_b205_f1ap.pcap
  f1u_enable: false
  f1u_filename: /tmp/du_b205_f1u.pcap