db_uri: mongodb://localhost/open5gs
logger:
  file:
    path: /home/acetcom/Documents/git/open5gs/install/var/log/open5gs/pcf.log
#  level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

pcf:
  sbi:
    server:
      - address: 127.0.1.13
        port: 7777
    client:
#      nrf:
#        - uri: http://127.0.0.10:7777
      scp:
        - uri: http://127.0.1.200:7777
  metrics:
    server:
      - address: 127.0.1.13
        port: 9090