logger:
  file:
    path: /home/acetcom/Documents/git/open5gs/install/var/log/open5gs/smf.log
#  level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

smf:
  sbi:
    server:
      - address: smf.5gc.mnc070.mcc999.3gppnetwork.org
    client:
#      nrf:
#        - uri: http://127.0.1.10:7777
      scp:
        - uri: http://127.0.1.200:7777
  pfcp:
    server:
      - address: 127.0.1.4
    client:
      upf:
        - address: 127.0.1.7
  gtpc:
    server:
      - address: 127.0.1.4
  gtpu:
    server:
      - address: 127.0.1.4
  metrics:
    server:
      - address: 127.0.1.4
        port: 9090
  session:
    - subnet: 10.46.0.0/16
      gateway: 10.46.0.1
    - subnet: 2001:db8:babe::/48
      gateway: 2001:db8:babe::1
  dns:
    - 8.8.8.8
    - 8.8.4.4
    - 2001:4860:4860::8888
    - 2001:4860:4860::8844
  mtu: 1400